# -*- coding: utf-8 -*-
# Fill the gallery's full-source blocks: in index.html,
#   <details class="codebox" data-egi="<path under examples/>">...</details>
#   <details class="codebox" data-fmr="<path under examples/>">...</details>
# get their bodies replaced with the current content of that file
# (escaped, with a line-count summary).  Idempotent -- run it again
# whenever an example or its generated .fmr changes.
import io, os, re, html

HERE = os.path.dirname(os.path.abspath(__file__))
GALLERY = os.path.join(HERE, '..')
EXAMPLES = os.path.join(GALLERY, '..', 'examples')
INDEX = os.path.join(GALLERY, 'index.html')

def load(rel, comment_re):
    src = io.open(os.path.join(EXAMPLES, rel), encoding='utf-8').read().rstrip('\n')
    nlines = src.count('\n') + 1
    body = html.escape(src, quote=False)
    body = re.sub(comment_re, r'<span class="c">\1</span>', body)
    return body, nlines

def egi(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    label = ('生成された Egison(中間形・fec.py 出力)'
             if 'GENERATED by tools/fec.py' in body else 'Egison ソース全文')
    return ('<details class="codebox" data-egi="%s"><summary>%s'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, label, os.path.basename(rel), n, body))


def fe(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    return ('<details class="codebox" data-fe="%s" open><summary>DSL ソース全文'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, os.path.basename(rel), n, body))

def fmr(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(#.*)$')
    return ('<details class="codebox" data-fmr="%s"><summary>生成された Formura 全文'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, os.path.basename(rel), n, body))

for page in [INDEX, os.path.join(GALLERY, 'dsl', 'index.html')]:
    if not os.path.exists(page):
        continue
    s = io.open(page, encoding='utf-8').read()
    s, n0 = re.subn(r'<details class="codebox" data-fe="(?P<rel>[^"]+)"[^>]*>.*?</details>', fe, s, flags=re.S)
    s, n1 = re.subn(r'<details class="codebox" data-egi="(?P<rel>[^"]+)">.*?</details>', egi, s, flags=re.S)
    s, n2 = re.subn(r'<details class="codebox" data-fmr="(?P<rel>[^"]+)">.*?</details>', fmr, s, flags=re.S)
    io.open(page, 'w', encoding='utf-8').write(s)
    print('%s: embedded %d .fe + %d .egi + %d .fmr' % (os.path.relpath(page, GALLERY), n0, n1, n2))
