# -*- coding: utf-8 -*-
# Fill the gallery's full-source blocks: in html/{ja,en}/gallery.html,
#   <details class="codebox" data-fme="<path under examples/>">...</details>
#   <details class="codebox" data-egi="<path under examples/>">...</details>
#   <details class="codebox" data-feir="<path under examples/>">...</details>
#   <details class="codebox" data-fmr="<path under examples/>">...</details>
# get their bodies replaced with the current content of that file
# (escaped, with a line-count summary).  Idempotent -- run it again
# whenever an example or any generated normalization artifact changes.
import io, os, re, html

HERE = os.path.dirname(os.path.abspath(__file__))
GALLERY = os.path.join(HERE, '..')
ROOT = os.path.join(GALLERY, '..')
EXAMPLES = os.path.join(ROOT, 'examples')

JA = {
    'fme': 'Formurae ソース全文(%s・%d 行)',
    'egi_generated': '生成された Egison normalization unit(formurae-pre 出力)(%s・%d 行)',
    'egi_plain': 'Egison ソース全文(%s・%d 行)',
    'feir': 'Egison 正規化結果 FEIR(%s・%d 行)',
    'feir_inject': 'Egison 正規化結果 FEIR',
    'fmr': '生成された Formura 全文(%s・%d 行)',
}
EN = {
    'fme': 'Full Formurae source (%s, %d lines)',
    'egi_generated': 'Generated Egison normalization unit (formurae-pre output) (%s, %d lines)',
    'egi_plain': 'Full Egison source (%s, %d lines)',
    'feir': 'FEIR after Egison normalization (%s, %d lines)',
    'feir_inject': 'FEIR after Egison normalization',
    'fmr': 'Full generated Formura source (%s, %d lines)',
}
PAGES = [
    (os.path.join(ROOT, 'html', 'ja', 'gallery.html'), JA),
    (os.path.join(ROOT, 'html', 'en', 'gallery.html'), EN),
]

def load(rel, comment_re):
    src = io.open(os.path.join(EXAMPLES, rel), encoding='utf-8').read().rstrip('\n')
    nlines = src.count('\n') + 1
    body = html.escape(src, quote=False)
    body = re.sub(comment_re, r'<span class="c">\1</span>', body)
    return body, nlines

def egi(labels, m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    key = 'egi_generated' if 'GENERATED by' in body else 'egi_plain'
    label = labels[key] % (os.path.basename(rel), n)
    return ('<details class="codebox" data-egi="%s"><summary>%s</summary>\n'
            '<pre>%s</pre></details>' % (rel, label, body))

def fme(labels, m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    label = labels['fme'] % (os.path.basename(rel), n)
    return ('<details class="codebox" data-fme="%s" open><summary>%s</summary>\n'
            '<pre>%s</pre></details>' % (rel, label, body))

def feir(labels, m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(;.*)$')
    label = labels['feir'] % (os.path.basename(rel), n)
    return ('<details class="codebox" data-feir="%s"><summary>%s</summary>\n'
            '<pre>%s</pre></details>' % (rel, label, body))

def fmr(labels, m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(#.*)$')
    label = labels['fmr'] % (os.path.basename(rel), n)
    return ('<details class="codebox" data-fmr="%s"><summary>%s</summary>\n'
            '<pre>%s</pre></details>' % (rel, label, body))

for page, labels in PAGES:
    s = io.open(page, encoding='utf-8').read()
    existing_feir = set(re.findall(r'data-feir="([^"]+)"', s))

    def inject_feir(m):
        block = m.group(0)
        rel = m.group('rel')
        candidate = os.path.splitext(rel)[0] + '.feir'
        path = os.path.join(EXAMPLES, candidate)
        if candidate in existing_feir or not os.path.exists(path):
            return block
        existing_feir.add(candidate)
        return (block + '\n  <details class="codebox" data-feir="%s">'
                '<summary>%s</summary></details>'
                % (candidate, labels['feir_inject']))

    s = re.sub(r'<details class="codebox" data-egi="(?P<rel>[^"]+)">.*?</details>',
               inject_feir, s, flags=re.S)
    s, n0 = re.subn(r'<details class="codebox" data-fme="(?P<rel>[^"]+)"(?P<attrs>[^>]*)>.*?</details>',
                    lambda m: fme(labels, m), s, flags=re.S)
    s, n1 = re.subn(r'<details class="codebox" data-egi="(?P<rel>[^"]+)">.*?</details>',
                    lambda m: egi(labels, m), s, flags=re.S)
    s, n2 = re.subn(r'<details class="codebox" data-feir="(?P<rel>[^"]+)">.*?</details>',
                    lambda m: feir(labels, m), s, flags=re.S)
    s, n3 = re.subn(r'<details class="codebox" data-fmr="(?P<rel>[^"]+)"[^>]*>.*?</details>',
                    lambda m: fmr(labels, m), s, flags=re.S)
    io.open(page, 'w', encoding='utf-8').write(s)
    print('%s: embedded %d .fme + %d .egi + %d .feir + %d .fmr'
          % (os.path.relpath(page, ROOT), n0, n1, n2, n3))
