# -*- coding: utf-8 -*-
# Fill the gallery's full-source blocks: in index.html,
#   <details class="codebox" data-fme="<path under examples/>">...</details>
#   <details class="codebox" data-egi="<path under examples/>">...</details>
#   <details class="codebox" data-feir="<path under examples/>">...</details>
#   <details class="codebox" data-fmr="<path under examples/>">...</details>
# get their bodies replaced with the current content of that file
# (escaped, with a line-count summary).  Idempotent -- run it again
# whenever an example or any generated normalization artifact changes.
import io, os, re, html

HERE = os.path.dirname(os.path.abspath(__file__))
GALLERY = os.path.join(HERE, '..')
EXAMPLES = os.path.join(GALLERY, '..', 'examples')
INDEX = os.path.join(GALLERY, 'index.html')

def load(rel, comment_re):
    src = io.open(os.path.join(EXAMPLES, rel), encoding='utf-8').read().rstrip('\n')
    nlines = src.count('\n') + 1
    body = html.escape(src, quote=False)
    body = re.sub(comment_re, r'<span class="c">\1</span>', body)
    return body, nlines

def egi(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    label = ('生成された Egison normalization unit(pre-fec 出力)'
             if 'GENERATED by' in body else 'Egison ソース全文')
    return ('<details class="codebox" data-egi="%s"><summary>%s'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, label, os.path.basename(rel), n, body))


def fme(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(--.*)$')
    return ('<details class="codebox" data-fme="%s" open><summary>Formurae ソース全文'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, os.path.basename(rel), n, body))

def feir(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(;.*)$')
    return ('<details class="codebox" data-feir="%s"><summary>Egison 正規化結果 FEIR'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, os.path.basename(rel), n, body))

def fmr(m):
    rel = m.group('rel')
    body, n = load(rel, r'(?m)^(#.*)$')
    return ('<details class="codebox" data-fmr="%s"><summary>生成された Formura 全文'
            '(%s・%d 行)</summary>\n<pre>%s</pre></details>'
            % (rel, os.path.basename(rel), n, body))

for page in [INDEX, os.path.join(GALLERY, 'dsl', 'index.html')]:
    if not os.path.exists(page):
        continue
    s = io.open(page, encoding='utf-8').read()
    existing_feir = set(re.findall(r'data-feir="([^"]+)"', s))

    def inject_feir(m):
        block = m.group(0)
        rel = m.group('rel')
        candidate = os.path.splitext(rel)[0] + '.feir'
        path = os.path.join(EXAMPLES, candidate)
        if candidate in existing_feir or not os.path.exists(path):
            return block
        existing_feir.add(candidate)
        return (block + '\n  <details class="codebox" data-feir="%s">'
                '<summary>Egison 正規化結果 FEIR</summary></details>' % candidate)

    s = re.sub(r'<details class="codebox" data-egi="(?P<rel>[^"]+)">.*?</details>',
               inject_feir, s, flags=re.S)
    s, n0 = re.subn(r'<details class="codebox" data-fme="(?P<rel>[^"]+)"(?P<attrs>[^>]*)>.*?</details>', fme, s, flags=re.S)
    s, n1 = re.subn(r'<details class="codebox" data-egi="(?P<rel>[^"]+)">.*?</details>', egi, s, flags=re.S)
    s, n2 = re.subn(r'<details class="codebox" data-feir="(?P<rel>[^"]+)">.*?</details>', feir, s, flags=re.S)
    s, n3 = re.subn(r'<details class="codebox" data-fmr="(?P<rel>[^"]+)"[^>]*>.*?</details>', fmr, s, flags=re.S)
    io.open(page, 'w', encoding='utf-8').write(s)
    print('%s: embedded %d .fme + %d .egi + %d .feir + %d .fmr'
          % (os.path.relpath(page, GALLERY), n0, n1, n2, n3))
